### PR TITLE
add `uv_cond_t` libuv compat functions

### PR DESCRIPTION
**Pull request by TooTallNate**
For node v0.8.x legacy compat.

/cc @unbornchikken This is what I was thinking as far as retaining node v0.8.x compat. Let me know what you think.

### CODE REVIEW

**Comment by unbornchikken** [comment]
I have limited computing capabilities on this week, because I'm on holiday. If it works, then let's rock, place a 2.0 to npm.

**Comment by unbornchikken** [comment]
So, by my opinion this is not worth to hold our 2.0 release. If someone wants ffi for 0.8 by some pie-in-the-sky reason, we can put a note in the readme about what is the last version of ffi that supports 0.8.

**Comment by TooTallNate** [comment]
@unbornchikken I agree. I'll tag v2 now.

**Comment by TooTallNate** [comment]
Also, obviously this isn't as easy as I was hoping :(

**Pull request closed without merging**
