### PR TITLE
io.js and Node.0.12 support

### PR DESCRIPTION
**Pull request by unbornchikken**
It's based on https://github.com/node-ffi/node-ffi/pull/189. Notable changes:

- NAN upgraded
- libuv used for thread synchronization instead of pthreads, so pthreads Windows dependency has been dropped.
- Callback error handling reworked:
    - instead of TryCatch in DispatchToV8, the callback returns its error in the result, and this will be rethrown by using NanThrowError. Why? If DispatchToV8 called through WatcherCallback then TryCatch somehow prevented  error handling to work properly, and it's an easy fix to not catch anything in there just check the result. 
    - Also I've replaced deprecated node::FatalException call to a simple process.nextTick throw solution because FatalException is not work properly in io.js.
- I've updated some unit tests:
   - According to this issue: https://github.com/iojs/io.js/issues/1161 io.js not thows error when setting string value instead of integer on a Buffer. I've changed the string to a larger number, thats throws. 
   - In the current build C stdlib is not exported in the main executable on Windows, so I changed the tests to call libuv methods on this platform.

I've tried to configure my WebStorm to use the same coding rules as you are using. If you see any issues related to it, please tell, and I'll fix'em.

### CODE REVIEW

**Comment by unbornchikken** [comment]
Please note that automated tests fails only with Node 0.8. I've tried to fix this, but I could't even install node-gyp for Node 0.8.9 it failed because of glob install error. I think ffi should increase it's mayor version and drop 0.8 support for good in it. 

The AppVeyor complaint is only a deprecation warning, that is already fixed in npm side: https://github.com/npm/npm/commit/3e431f9d6884acb4cde8bcb8a0b122a76b33ee1d, but npm version in Node 0.12 is still affected by this.

**Comment by TooTallNate** [comment]
Nice stuff!

**Comment by TooTallNate** [comment]
Re: styling. It looks like you're using tab `\t` characters. The codebase uses 2-space soft tabs.

**Comment by TooTallNate** [comment]
You also seem to have included a lot of whitespace changes which make the diff harder to read:

``` diff
diff --git a/test/callback.js b/test/callback.js
index 06902d1..3b53ea0 100644
--- a/test/callback.js
+++ b/test/callback.js
@@ -1,28 +1,28 @@
-
 var assert = require('assert')
   , ref = require('ref')
   , ffi = require('../')
   , int = ref.types.int
-  , bindings = require('bindings')({ module_root: __dirname, bindings: 'ffi_tests' })
+  , bindings = require('bindings')({module_root: __dirname, bindings: 'ffi_tests'})

 describe('Callback', function () {

   afterEach(gc)

   it('should create a C function pointer from a JS function', function () {
-    var callback = ffi.Callback('void', [ ], function (val) { })
+    var callback = ffi.Callback('void', [], function (val) { })
     assert(Buffer.isBuffer(callback))
   })

   it('should be invokable by an ffi\'d ForeignFunction', function () {
-    var funcPtr = ffi.Callback(int, [ int ], Math.abs)
-    var func = ffi.ForeignFunction(funcPtr, int, [ int ])
+    var funcPtr = ffi.Callback(int, [int], Math.abs)
+    var func = ffi.ForeignFunction(funcPtr, int, [int])
     assert.equal(1234, func(-1234))
   })

   it('should work with a "void" return type', function () {
-    var funcPtr = ffi.Callback('void', [ ], function (val) { })
-    var func = ffi.ForeignFunction(funcPtr, 'void', [ ])
+    var funcPtr = ffi.Callback('void', [], function (val) {
+    })
+    var func = ffi.ForeignFunction(funcPtr, 'void', [])
```

**Comment by TooTallNate** [comment]
> In the current build C stdlib is not exported in the main executable on Windows, so I changed the tests to call libuv methods on this platform.

I think you're actually being bitten by https://github.com/dlfcn-win32/dlfcn-win32/issues/2. This issue has been fixed very recently, and I suspect that if we update the `deps/dlfcn-win32` directory to point to https://github.com/gypified/dlfcn-win32/commit/718d27cf55bc9765f2f6e501b694d788ba77775d, then those `strcpy()` tests would pass on Windows once again.

**Comment by unbornchikken** [comment]
Sorry, I was in a hurry. I'll fix ws issues asap. and try to integrate the recent dlfcn. Will tell if this PR gets ready to review.

About supporting 0.8. Should I try to fix it, or will you go with 0.10+ in the next release?

**Comment by unbornchikken** [comment]
Ok, I've checked Node 0.8 incompatibility. That's because we had switched thread synchronization from pthreads to libuv. Unfortunately required libuv construct (uv_cond_t) is not supported in 0.8. On the other hand pthread based synchronization doesn't seem to cooperate qith recent libuv based 0.12 and io.js, there was deadlocks on Windows because of this (fixed in https://github.com/unbornchikken/node-ffi/commit/e22ea8f1f9377a6fa0759affe01c2d27a701ede1).

So we have 0.8 support or 0.12/io.js support, not both. I suggest that we could go with 0.10+ and drop 0.8 support for good. For 0.8 users we can offer and older version from the npm.

So **I've changes Travis CI and AppVeyor configs to test with io.js and to not test 0.8. That's why you see a conflict.**

I did dlfcn update on a separate branch but I not be able to test it till tomorrow morning. I feed you back when it's done.

**Comment by TooTallNate** [comment]
I'm probably ok with dropping v0.8 support. A bit unfortunate, but not the end of the world.

**Comment by unbornchikken** [comment]
Maybe I should restore pthreads usage on POSIX, and use native synchronization constructs on Windows. But I don't think thats worth the time and effort. If someone using node from the last decade, he or she could access ffi of the last decade. It's already mature enough to not fear from that the switch causes anything like the python crisis. :)

**Comment by TooTallNate** [comment]
Nah don't bother. We'll live. I'm much happier getting all the tests passing on v0.10 and v0.12 consistently on unix _and_ Windows at this point.

Definitely curious about if those `strlen()` tests pass on Windows after the dlfcn-win32 update...

**Comment by unbornchikken** [comment]
Ok, it's there. New version of dlfcn did it, all of the original cases of library.js has been passed. Merged in https://github.com/node-ffi/node-ffi/commit/e8576bd1dc10da86170b99c20f345579c2ca1991. 

So the current status is:
- All of the original tests pass on Windows / Linux with Node 0.10, 0.12 and io.js. I've tested it with io.js 1.5.1.
- Whitespace changes fixed (atleast on files that I did change, if there are issues remain, please tell)

There is only one issue remains: the failed test of objc.js on OSX. I think I've catched the source of this error and fixed it in https://github.com/node-ffi/node-ffi/commit/dd12b6ab12ba5273acde0d3fe49b2d1ad44d1b54, but I'm not able to test it because I don't have an OSX.

**Comment by TooTallNate** [comment]
Looks great @unbornchikken! The ObjC failing test is fixed on v0.10, but for some reason v0.12 isn't passing that one. I don't think this is an problem in this PR though, so I'll plan on merging this a bit later today. Great work!

**Comment by TooTallNate** [comment]
Merged! Thanks a lot @unbornchikken

**Comment by unbornchikken** [comment]
That's how I pay for free software. ;)

**Comment by kjunichi** [comment]
+1

**Comment by kitak** [comment]
:+1:

**Pull request merged**
