### PR TITLE
NAN 2.0 support (done)

### PR DESCRIPTION
**Pull request by unbornchikken**
This is an in-progress PR. There is an issue that have to be resolved before merge. 

When callback queue items gets processed in CallbackInfo::WatcherCallback which is invoked by libuv uv_async_send(&g_async) in callback_info.cc 192, the control flow eventually reaches CallbackInfo::DispatchToV8 at line 71, and there is a Nan::NewBuffer call. But v8 crashes there by raising the following error:

```
FATAL ERROR: v8::HandleScope::CreateHandle() Cannot create a handle without a HandleScope
```
Which is odd because there is a Nan::HandleScope on top of DispatchToV8 definitely (at line 53).

io.js 1.x is not affected, I'm getting this with 2.5. I believe that there is some magic required to make a bare libuv callback v8 GC compatible that is not present in the new Nan::HandleScope.

### CODE REVIEW

**Comment by unbornchikken** [comment]
@TooTallNate Do you know someone in the NAN team who might willing to help us? I think the solution have to be pretty obvious for someone with a good internal knowledge of NAN. If you could summon someone there, I'm gonna lead him to the issue if the above description is too sparse.

**Comment by TooTallNate** [comment]
It's like V8 all over again :fearful:

**Comment by kkoopa** [comment]
https://github.com/unbornchikken/node-ffi/pull/1

**Comment by unbornchikken** [comment]
Ok, that helped, thanks a lot. However 0.10 is still failing, but I'm gonna fix it later today or tomorrow. The main issue was the recent v8 compatibility.

**Comment by unbornchikken** [comment]
@kkoopa I think there is and issue with the new Nan::NewBuffer on 0.10.40. It looks like its free callback never gets invoked after doing a gc.

Here we create a Buffer with a GC callback:
https://github.com/unbornchikken/node-ffi/blob/nan2/src/callback_info.cc#L153 at https://github.com/unbornchikken/node-ffi/blob/nan2/src/callback_info.cc#L39

There is an unit test, where we nullify the reference of the above Buffer followed by a gc() call:

https://github.com/unbornchikken/node-ffi/blob/nan2/test/callback.js#L82

This should invoke that free callback, but it never happens on 0.10.40. 0.12 and io.js is OK.

Is this really a NAN issue or am I screwing up something?

**Comment by kkoopa** [comment]
Likely fixed in nodejs/nan@bc45db2cf12287816839ade47c1f7f3353f440e9. Try the [memleak branch](https://github.com/nodejs/nan/pull/392).

**Comment by unbornchikken** [comment]
I can confirm that this commit fixes the above Buffer issue. Cool. Now, we gotta wait while this gets released then ffi's NAN 2.0 support gets completed.

Thak you again!

**Comment by unbornchikken** [comment]
@TooTallNate now ffi's side is completed, you could merge this. But unfortunately install gets failed with io.js 3.0.0 because ref doesn't have NAN 2.0 support implemented.

**Comment by Mitko-Kerezov** [comment]
As of https://github.com/TooTallNate/ref/commit/563af1abc11a7af229765594e83d216867e23f69 ref does have support for NAN 2.0 so I assume this PR can safely be merged, @TooTallNate ?

**Comment by unbornchikken** [comment]
Refer to the PR's title: *Io.js 3.0 support -(blocked, waiting for nodejs/node#2487 gets released) *

**Comment by unbornchikken** [comment]
But I can see that commit has been deployed in io.js 3.2. I'll have to check it later.

**Comment by unbornchikken** [comment]
I'm closing this. Gonna open up an other PR for this with a corrected commit history. @kkoopa thank you for your help again!

**Pull request closed without merging**
