### PR TITLE
io.js 1.7+ support + test case covering #199

### PR DESCRIPTION
**Pull request by unbornchikken**
It fixes https://github.com/node-ffi/node-ffi/issues/201.

Despite this PR has a long history of commits, it only includes a line to callback_info.cc. I switched my master to mirror node-ffi master today.

### CODE REVIEW

**Comment by unbornchikken** [comment]
It looks like Travis is happy again, hallelujah! \o/

**Comment by unbornchikken** [comment]
New stuff has landed. I've added a test case covering https://github.com/node-ffi/node-ffi/issues/199

**Comment by unbornchikken** [comment]
AppVeyor fails because of: https://github.com/iojs/io.js/issues/751 there is nothing we can do about it I'm afraid.

**Comment by TooTallNate** [comment]
We should squash when we merge this :)

Thanks for looking into it @unbornchikken!

**Comment by TooTallNate** [comment]
Merged as 2 commits: c724fa1285126efa335b9feb9f79acd7d8242f8d and 403d821ed8492e86de14b186d0360e7814d61952.

Thanks @unbornchikken!

**Comment by TooTallNate** [comment]
ffi@1.3.1 has been published to npm as well.

**Comment by unbornchikken** [comment]
Since there is no chance that I'll be in San Francisco in the near future and I really dubt that you're willing to travel to Dagoba System, we could do a little adventuring on Dungeons and Drangons Online instead, eh? I can even offer a position for ya in my clan. :D

**Pull request closed without merging**
