### PR TITLE
New dlfcn-win32 PR has landed and integrated there (in progress)

### PR DESCRIPTION
**Pull request by unbornchikken**
Unicode support PR has just landed at dlfcn-win32. This PR integrate it there. That should fix https://github.com/node-ffi/node-ffi/issues/183

### CODE REVIEW

**Comment by TooTallNate** [comment]
Maybe we should add a regression test if possible

**Comment by unbornchikken** [comment]
Tomorrow I'll have acces to a windows, and try to invent something to test this properly.

**Comment by unbornchikken** [comment]
Added a test case, but unfortunatelly it still doesn't load libraries in unicode path names. I'll investigate this later, maybe I could invent a PR for dlfcn-win32 that solves our issue there. At least we have a test case that triggers https://github.com/node-ffi/node-ffi/issues/183.

**Comment by unbornchikken** [comment]
clsed in favor of https://github.com/node-ffi/node-ffi/pull/226

**Pull request closed without merging**
