### PR TITLE
Move `errno` method implement to C++ side

### LINKED ISSUE #273: "Symbol not found: errno" when running `npm test` on Alpine Linux (musl)
[Alpine Linux](http://www.alpinelinux.org/) is [musl-based](http://www.musl-libc.org/) instead of glibc-based, so this may be the root cause of the issue.

It would be great to get ffi working on Alpine Linux though – especially because of the [tiny Node.js Docker images](https://hub.docker.com/r/mhart/alpine-node/) that you can create with it.

The full details of the error are below:
```sh
$ npm test

> ffi@2.0.0 test /node_modules/ffi
> node-gyp rebuild --directory test && mocha -gc --reporter spec

make: Entering directory '/node_modules/ffi/test/build'
  CXX(target) Release/obj.target/ffi_tests/ffi_tests.o
  SOLINK_MODULE(target) Release/obj.target/ffi_tests.node
  COPY Release/ffi_tests.node
make: Leaving directory '/node_modules/ffi/test/build'
/node_modules/ffi/lib/dynamic_library.js:112
    throw new Error('Dynamic Symbol Retrieval Error: ' + this.error())
    ^

Error: Dynamic Symbol Retrieval Error: Symbol not found: errno
    at DynamicLibrary.get (/node_modules/ffi/lib/dynamic_library.js:112:11)
    at Object.<anonymous> (/node_modules/ffi/lib/errno.js:27:38)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/node_modules/ffi/lib/ffi.js:83:17)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/node_modules/ffi/test/callback.js:3:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /node_modules/ffi/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/node_modules/ffi/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/node_modules/ffi/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/node_modules/ffi/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```

### PR DESCRIPTION
**Pull request by d3m3vilurr**
`errno` value depend on the platform and libc library.
For example, `glibc` and `musl` differ `errno.h`

So, Sometimes `lib/errno.js` implement cannot be use.

Reference:
- http://sourceware.org/git/?p=glibc.git;a=blob;f=include/errno.h;h=7df41dfc3#l35
- http://git.musl-libc.org/cgit/musl/tree/include/errno.h?id=2d0290de#n13

Fix #273

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks for the PR. I agree that this is probably the better way to go. However, Windows tests are failing now. Any ideas what's up?

**Comment by d3m3vilurr** [comment]
Hi @TooTallNate 
I'm not have windows develop environment :(  (only have linux box)
But, `errno` macro was defined in the `errno.h`
https://msdn.microsoft.com/ko-kr/library/t3ayayh1.aspx

PS. Anyway, I will try to test this problem in the vbox+windows :)

PS2. BTW, this patch not enough to use module in the musl environ, it just fix about load module problem.

I tested today, `npm test` always raise segfault in the alpine linux.
And few hours ago, found solution, `libffi` need to version up to `3.2.1` and apply musl support patch.
So, I will make new pr asap, but now try to find another `configure` method instead of `deps/libffi/config` directory(also it need to test windows system, too.)

**Comment by d3m3vilurr** [comment]
@TooTallNate i'm give up windows problem. recovered windows part of `lib/errno.js`..

**Comment by Vanuan** [comment]
So, can this be merged?

**Comment by d3m3vilurr** [comment]
@Vanuan yes :) but if you use on the musl environ, also require merge #285.
both pr worked done. (I not tested on bsd environ, but it will be working)

@TooTallNate @unbornchikken can you review these pr?

**Comment by unbornchikken** [comment]
Both works at my side. However, there are some other supported platforms than Linux, OSX and Windows. By my opinion, we could release those PRs in a new major, and after we can fix occasionally appearing problems of other platforms in HF releases. @TooTallNate , what do you say?

**Comment by pkoretic** [comment]
Any news on this one :) ?

**Comment by d3m3vilurr** [comment]
@TooTallNate @unbornchikken any update these #284 #285 pr?

**Pull request closed without merging**
