### PR TITLE
Set nan dependency to <2.0.0 because of a breaking API change.

### PR DESCRIPTION
**Pull request by feldgendler**
A stop-gap solution to #215.

### CODE REVIEW

**Comment by TooTallNate** [comment]
We should just do `1` instead. Otherwise <1.0.0 could potentially be used as well.

**Comment by feldgendler** [comment]
Are you sure you're not using anything from a higher version? 1.9 maybe?

**Comment by TooTallNate** [comment]
I don't understand your question. `1` means `>= 1.0.0 && < 2.0.0`.

**Comment by feldgendler** [comment]
I was asking whether an even stricter version specification was more appropriate. Now that you brought it up, "1" might still be too permissive.

**Pull request closed without merging**
