### PR TITLE
Support Node.js 9.x version

### PR DESCRIPTION
**Pull request by zhaoda**

### CODE REVIEW

**Comment by bnoordhuis** [comment]
@zhaoda Can I suggest you add node 8 and 9 to `.travis.yml` ([here](https://github.com/node-ffi/node-ffi/blob/6048e686c4cc4b01edb6054b7ad8e74bb267eacf/.travis.yml#L19)) and maybe drop v0.10 and v0.12?  They can't be tested anymore because mocha no longer supports them.

**Comment by TooTallNate** [comment]
Thanks! I'll take care of you suggestions @bnoordhuis

**Comment by alexeykuzmin** [comment]
@TooTallNate are you going to publish a new version with the Node.js 9 support?

**Comment by TooTallNate** [comment]
Well the tests are seg faulting on Node 9 at the moment. If somebody has
some free cycles to look into that it would help.

**Comment by bnoordhuis** [comment]
I had a real quick look and the crashes appear to be `cif->arg_types` and `cif->rtype` pointers pointing to invalid memory locations - sometimes 0, sometimes a random address.

From a quick reading of the source:

1. the test creates a `ffi.Callback` object
2. then drops the reference to said object
3. calls `gc()` to reclaim the cif memory
4. memory is written over while still in use by libffi

If it works with older node.js versions, that's probably purely accidental.

**Comment by sayalisha** [comment]
Trying to install ffi on Ubuntu 16.04
node : v9.2.1
npm : 5.6.0

I get following error when installing ffi : 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.4.0-104-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/<>/Study/NodeJS/Code/electron-quick-start/node_modules/ffi
gyp ERR! node -v v9.2.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@2.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <path>/_logs/2018-01-05T06_36_29_822Z-debug.log

Does ffi have any issues with node 9?
Please help me in this!

**Comment by hibiyasleep** [comment]
Can you release v2.2.1 of ffi with this PR included?

**Comment by brandonkirsch** [comment]
https://github.com/node-ffi/node-ffi/commit/811ad02e730d40d0402aef63148b32f830e738de

This pull request seems to fix my build issue on Windows 7 + NWJS 0.28.1 (32-bit) + Visual Studio 2015.

Initial testing with some 3rd party DLLs seems to work.

**Comment by VishwasShashidhar** [comment]
Folks, it'll really help if the above mentioned fix is released. Thanks.

**Comment by VishwasShashidhar** [comment]
@TooTallNate Can you please release this? We've been waiting for a long time now. We'll also need to support node 10.x, I'll create another issue for that.

**Comment by belloyang** [comment]
hi @berkon I encountered with the same issue with my electron project. Do you happen to know of any workaround before this patch is released? Thank you

**Comment by berkon** [comment]
@belloyang, yes there has obviously already been a patch which fixes the issue. You could also do the modifications by yourself quite easily:

https://github.com/node-ffi/node-ffi/pull/439/commits/84e18178e6bae77cc15c9044da7ea8ccb081b037

Its not clear to me why they don't release a new version. The changes are really minor, but would help a lot.

**Pull request merged**
